-- go-migrate-safe v0.1.0
-- Version: 3
-- Name: add_order_items_table_and_add_orders_table
-- Direction: UP
-- Generated: 2026-08-15T08:26:34Z
-- Checksum: sha256:2957a1a7faca9f0b46c2e079d09fe6c028c61ed43170cefc50ecb0725de8853b
--
-- Operations (5):
--   [1] add_table: order_items
--   [2] add_table: orders
--   [3] add_table: product_categories
--   [4] add_table: products
--   [5] add_table: users
--
-- DO NOT EDIT this file after it has been applied to any environment.
-- To change the schema, create a new migration.

-- Logic: Grouped by table for performance
-- [1/5] add_table: order_items (Reason: Added "order_items" table (6 columns) — matches new struct)
-- [2/5] add_table: orders (Reason: Added "orders" table (6 columns) — matches new struct)
-- [3/5] add_table: product_categories (Reason: Added "product_categories" table (5 columns) — matches new struct)
-- [4/5] add_table: products (Reason: Added "products" table (10 columns) — matches new struct)
-- [5/5] add_table: users (Reason: Added "users" table (7 columns) — matches new struct)

CREATE TABLE IF NOT EXISTS order_items (
    id          BIGSERIAL        PRIMARY KEY,
    order_id    BIGINT           NOT NULL,
    product_id  BIGINT           NOT NULL,
    quantity    INTEGER          NOT NULL DEFAULT 1,
    price       DOUBLE PRECISION NOT NULL,
    created_at  TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id          BIGSERIAL        PRIMARY KEY,
    user_id     BIGINT           NOT NULL,
    status      TEXT             NOT NULL DEFAULT 'pending',
    total       DOUBLE PRECISION NOT NULL DEFAULT 0.00,
    created_at  TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_categories (
    id           BIGSERIAL   PRIMARY KEY,
    name         TEXT        NOT NULL,
    slug         TEXT        NOT NULL,
    description  TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id           BIGSERIAL        PRIMARY KEY,
    category_id  BIGINT           NOT NULL,
    name         TEXT             NOT NULL,
    slug         TEXT             NOT NULL,
    details      TEXT             NOT NULL,
    price        DOUBLE PRECISION NOT NULL DEFAULT 0.00,
    stock        INTEGER          NOT NULL DEFAULT 0,
    image_url    TEXT             NOT NULL,
    created_at   TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id             BIGSERIAL   PRIMARY KEY,
    username       TEXT        NOT NULL,
    email          TEXT        NOT NULL,
    password_hash  TEXT        NOT NULL,
    role           TEXT        NOT NULL DEFAULT 'user',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
