-- go-migrate-safe v0.1.0
-- Version: 1
-- Name: add_categories_table_and_add_order_items_table
-- Direction: DOWN
-- Generated: 2026-05-08T10:19:51Z
--
-- Operations (5):
--   [1] add_table: categories
--   [2] add_table: order_items
--   [3] add_table: orders
--   [4] add_table: products
--   [5] add_table: users
--
-- DO NOT EDIT this file after it has been applied to any environment.
-- To change the schema, create a new migration.

-- Rollback SQL to be populated by Rollback Agent.

-- [1/5] (rollback) drop_table: users
-- Reason: Inverse of add_table users
DROP TABLE IF EXISTS users;

-- [2/5] (rollback) drop_table: products
-- Reason: Inverse of add_table products
DROP TABLE IF EXISTS products;

-- [3/5] (rollback) drop_table: orders
-- Reason: Inverse of add_table orders
DROP TABLE IF EXISTS orders;

-- [4/5] (rollback) drop_table: order_items
-- Reason: Inverse of add_table order_items
DROP TABLE IF EXISTS order_items;

-- [5/5] (rollback) drop_table: categories
-- Reason: Inverse of add_table categories
DROP TABLE IF EXISTS categories;

