-- go-migrate-safe v0.1.0
-- Version: 1
-- Name: add_categories_table_and_add_order_items_table
-- Direction: UP
-- Generated: 2026-05-08T10:19:51Z
-- Checksum: sha256:cefb1bfbcb2b983eeb99c81d351c474c369db44f058ce072426351d3ed7cc5fd
--
-- Operations (5):
--   [1] add_table: categories
--   [2] add_table: order_items
--   [3] add_table: orders
--   [4] add_table: products
--   [5] add_table: users
--
-- DO NOT EDIT this file after it has been applied to any environment.
-- To change the schema, create a new migration.

-- [1/5] add_table: categories
-- Reason: Added "categories" table (5 columns) — matches new struct
CREATE TABLE categories (
    id           BIGINT IDENTITY(1,1),
    name         NVARCHAR(MAX)        NOT NULL,
    slug         NVARCHAR(MAX)        NOT NULL,
    description  NVARCHAR(MAX)        NOT NULL,
    created_at   DATETIME2            NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- [2/5] add_table: order_items
-- Reason: Added "order_items" table (6 columns) — matches new struct
CREATE TABLE order_items (
    id          BIGINT IDENTITY(1,1),
    order_id    BIGINT               NOT NULL,
    product_id  BIGINT               NOT NULL,
    quantity    INT                  NOT NULL DEFAULT 1,
    price       FLOAT                NOT NULL,
    created_at  DATETIME2            NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- [3/5] add_table: orders
-- Reason: Added "orders" table (6 columns) — matches new struct
CREATE TABLE orders (
    id          BIGINT IDENTITY(1,1),
    user_id     BIGINT               NOT NULL,
    status      NVARCHAR(255)        NOT NULL DEFAULT 'pending',
    total       FLOAT                NOT NULL DEFAULT 0.00,
    created_at  DATETIME2            NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME2            NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- [4/5] add_table: products
-- Reason: Added "products" table (10 columns) — matches new struct
CREATE TABLE products (
    id           BIGINT IDENTITY(1,1),
    category_id  BIGINT               NOT NULL,
    name         NVARCHAR(MAX)        NOT NULL,
    slug         NVARCHAR(MAX)        NOT NULL,
    description  NVARCHAR(MAX)        NOT NULL,
    price        FLOAT                NOT NULL DEFAULT 0.00,
    stock        INT                  NOT NULL DEFAULT 0,
    image_url    NVARCHAR(MAX)        NOT NULL,
    created_at   DATETIME2            NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME2            NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- [5/5] add_table: users
-- Reason: Added "users" table (7 columns) — matches new struct
CREATE TABLE users (
    id             BIGINT IDENTITY(1,1),
    username       NVARCHAR(MAX)        NOT NULL,
    email          NVARCHAR(MAX)        NOT NULL,
    password_hash  NVARCHAR(MAX)        NOT NULL,
    role           NVARCHAR(255)        NOT NULL DEFAULT 'user',
    created_at     DATETIME2            NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME2            NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
