-- go-migrate-safe v0.1.0
-- Version: 2
-- Name: rename_products_details_and_more
-- Direction: DOWN
-- Generated: 2026-08-14T15:27:24Z
--
-- Operations (54):
--   [1] rename_column: products.details
--   [2] rename_table: categories
--   [3] drop_table: _migrate_history
--   [4] drop_table: sysdiagrams
--   [5] add_index: orders
--   [6] add_index: product_categories
--   [7] add_index: products
--   [8] add_index: products
--   [9] add_index: users
--   [10] add_index: users
--   [11] add_constraint: order_items
--   [12] add_constraint: order_items
--   [13] add_constraint: orders
--   [14] add_constraint: products
--   [15] add_constraint: order_items
--   [16] add_constraint: orders
--   [17] add_constraint: product_categories
--   [18] add_constraint: products
--   [19] add_constraint: products
--   [20] add_constraint: users
--   [21] alter_column: order_items.id
--   [22] alter_column: order_items.order_id
--   [23] alter_column: order_items.product_id
--   [24] alter_column: order_items.quantity
--   [25] alter_column: order_items.price
--   [26] alter_column: order_items.created_at
--   [27] alter_column: orders.id
--   [28] alter_column: orders.user_id
--   [29] alter_column: orders.status
--   [30] alter_column: orders.total
--   [31] alter_column: orders.created_at
--   [32] alter_column: orders.updated_at
--   [33] alter_column: product_categories.id
--   [34] alter_column: product_categories.name
--   [35] alter_column: product_categories.slug
--   [36] alter_column: product_categories.description
--   [37] alter_column: product_categories.created_at
--   [38] alter_column: products.id
--   [39] alter_column: products.category_id
--   [40] alter_column: products.name
--   [41] alter_column: products.slug
--   [42] alter_column: products.details
--   [43] alter_column: products.price
--   [44] alter_column: products.stock
--   [45] alter_column: products.image_url
--   [46] alter_column: products.created_at
--   [47] alter_column: products.updated_at
--   [48] alter_column: users.id
--   [49] alter_column: users.username
--   [50] alter_column: users.email
--   [51] alter_column: users.password_hash
--   [52] alter_column: users.role
--   [53] alter_column: users.created_at
--   [54] alter_column: users.updated_at
--
-- DO NOT EDIT this file after it has been applied to any environment.
-- To change the schema, create a new migration.

-- Rollback SQL to be populated by Rollback Agent.

-- [1/54] (rollback) alter_column: users.updated_at
-- Reason: Inverse of alter_column users.updated_at
ALTER TABLE users ALTER COLUMN updated_at SET DATA TYPE datetime2;
ALTER TABLE users ALTER COLUMN updated_at SET DEFAULT (getdate());

-- [2/54] (rollback) alter_column: users.created_at
-- Reason: Inverse of alter_column users.created_at
ALTER TABLE users ALTER COLUMN created_at SET DATA TYPE datetime2;
ALTER TABLE users ALTER COLUMN created_at SET DEFAULT (getdate());

-- [3/54] (rollback) alter_column: users.role
-- Reason: Inverse of alter_column users.role
ALTER TABLE users ALTER COLUMN role SET DATA TYPE nvarchar;
ALTER TABLE users ALTER COLUMN role SET DEFAULT ('user');

-- [4/54] (rollback) alter_column: users.password_hash
-- Reason: Inverse of alter_column users.password_hash
ALTER TABLE users ALTER COLUMN password_hash SET DATA TYPE nvarchar;

-- [5/54] (rollback) alter_column: users.email
-- Reason: Inverse of alter_column users.email
ALTER TABLE users ALTER COLUMN email SET DATA TYPE nvarchar;

-- [6/54] (rollback) alter_column: users.username
-- Reason: Inverse of alter_column users.username
ALTER TABLE users ALTER COLUMN username SET DATA TYPE nvarchar;

-- [7/54] (rollback) alter_column: users.id
-- Reason: Inverse of alter_column users.id
ALTER TABLE users ALTER COLUMN id SET DATA TYPE bigint;

-- [8/54] (rollback) alter_column: products.updated_at
-- Reason: Inverse of alter_column products.updated_at
ALTER TABLE products ALTER COLUMN updated_at SET DATA TYPE datetime2;
ALTER TABLE products ALTER COLUMN updated_at SET DEFAULT (getdate());

-- [9/54] (rollback) alter_column: products.created_at
-- Reason: Inverse of alter_column products.created_at
ALTER TABLE products ALTER COLUMN created_at SET DATA TYPE datetime2;
ALTER TABLE products ALTER COLUMN created_at SET DEFAULT (getdate());

-- [10/54] (rollback) alter_column: products.image_url
-- Reason: Inverse of alter_column products.image_url
ALTER TABLE products ALTER COLUMN image_url SET DATA TYPE nvarchar;

-- [11/54] (rollback) alter_column: products.stock
-- Reason: Inverse of alter_column products.stock
ALTER TABLE products ALTER COLUMN stock SET DATA TYPE int;
ALTER TABLE products ALTER COLUMN stock SET DEFAULT ((0));

-- [12/54] (rollback) alter_column: products.price
-- Reason: Inverse of alter_column products.price
ALTER TABLE products ALTER COLUMN price SET DATA TYPE float;
ALTER TABLE products ALTER COLUMN price SET DEFAULT ((0.00));

-- [13/54] (rollback) alter_column: products.details
-- Reason: Inverse of alter_column products.details
ALTER TABLE products ALTER COLUMN details SET DATA TYPE nvarchar;

-- [14/54] (rollback) alter_column: products.slug
-- Reason: Inverse of alter_column products.slug
ALTER TABLE products ALTER COLUMN slug SET DATA TYPE nvarchar;

-- [15/54] (rollback) alter_column: products.name
-- Reason: Inverse of alter_column products.name
ALTER TABLE products ALTER COLUMN name SET DATA TYPE nvarchar;

-- [16/54] (rollback) alter_column: products.category_id
-- Reason: Inverse of alter_column products.category_id
ALTER TABLE products ALTER COLUMN category_id SET DATA TYPE bigint;

-- [17/54] (rollback) alter_column: products.id
-- Reason: Inverse of alter_column products.id
ALTER TABLE products ALTER COLUMN id SET DATA TYPE bigint;

-- [18/54] (rollback) alter_column: product_categories.created_at
-- Reason: Inverse of alter_column product_categories.created_at
ALTER TABLE product_categories ALTER COLUMN created_at SET DATA TYPE datetime2;
ALTER TABLE product_categories ALTER COLUMN created_at SET DEFAULT (getdate());

-- [19/54] (rollback) alter_column: product_categories.description
-- Reason: Inverse of alter_column product_categories.description
ALTER TABLE product_categories ALTER COLUMN description SET DATA TYPE nvarchar;

-- [20/54] (rollback) alter_column: product_categories.slug
-- Reason: Inverse of alter_column product_categories.slug
ALTER TABLE product_categories ALTER COLUMN slug SET DATA TYPE nvarchar;

-- [21/54] (rollback) alter_column: product_categories.name
-- Reason: Inverse of alter_column product_categories.name
ALTER TABLE product_categories ALTER COLUMN name SET DATA TYPE nvarchar;

-- [22/54] (rollback) alter_column: product_categories.id
-- Reason: Inverse of alter_column product_categories.id
ALTER TABLE product_categories ALTER COLUMN id SET DATA TYPE bigint;

-- [23/54] (rollback) alter_column: orders.updated_at
-- Reason: Inverse of alter_column orders.updated_at
ALTER TABLE orders ALTER COLUMN updated_at SET DATA TYPE datetime2;
ALTER TABLE orders ALTER COLUMN updated_at SET DEFAULT (getdate());

-- [24/54] (rollback) alter_column: orders.created_at
-- Reason: Inverse of alter_column orders.created_at
ALTER TABLE orders ALTER COLUMN created_at SET DATA TYPE datetime2;
ALTER TABLE orders ALTER COLUMN created_at SET DEFAULT (getdate());

-- [25/54] (rollback) alter_column: orders.total
-- Reason: Inverse of alter_column orders.total
ALTER TABLE orders ALTER COLUMN total SET DATA TYPE float;
ALTER TABLE orders ALTER COLUMN total SET DEFAULT ((0.00));

-- [26/54] (rollback) alter_column: orders.status
-- Reason: Inverse of alter_column orders.status
ALTER TABLE orders ALTER COLUMN status SET DATA TYPE nvarchar;
ALTER TABLE orders ALTER COLUMN status SET DEFAULT ('pending');

-- [27/54] (rollback) alter_column: orders.user_id
-- Reason: Inverse of alter_column orders.user_id
ALTER TABLE orders ALTER COLUMN user_id SET DATA TYPE bigint;

-- [28/54] (rollback) alter_column: orders.id
-- Reason: Inverse of alter_column orders.id
ALTER TABLE orders ALTER COLUMN id SET DATA TYPE bigint;

-- [29/54] (rollback) alter_column: order_items.created_at
-- Reason: Inverse of alter_column order_items.created_at
ALTER TABLE order_items ALTER COLUMN created_at SET DATA TYPE datetime2;
ALTER TABLE order_items ALTER COLUMN created_at SET DEFAULT (getdate());

-- [30/54] (rollback) alter_column: order_items.price
-- Reason: Inverse of alter_column order_items.price
ALTER TABLE order_items ALTER COLUMN price SET DATA TYPE float;

-- [31/54] (rollback) alter_column: order_items.quantity
-- Reason: Inverse of alter_column order_items.quantity
ALTER TABLE order_items ALTER COLUMN quantity SET DATA TYPE int;
ALTER TABLE order_items ALTER COLUMN quantity SET DEFAULT ((1));

-- [32/54] (rollback) alter_column: order_items.product_id
-- Reason: Inverse of alter_column order_items.product_id
ALTER TABLE order_items ALTER COLUMN product_id SET DATA TYPE bigint;

-- [33/54] (rollback) alter_column: order_items.order_id
-- Reason: Inverse of alter_column order_items.order_id
ALTER TABLE order_items ALTER COLUMN order_id SET DATA TYPE bigint;

-- [34/54] (rollback) alter_column: order_items.id
-- Reason: Inverse of alter_column order_items.id
ALTER TABLE order_items ALTER COLUMN id SET DATA TYPE bigint;

-- [35/54] (rollback) drop_constraint: users
-- Reason: Inverse of add_constraint pk_users
ALTER TABLE users DROP CONSTRAINT IF EXISTS pk_users;

-- [36/54] (rollback) drop_constraint: products
-- Reason: Inverse of add_constraint pk_products
ALTER TABLE products DROP CONSTRAINT IF EXISTS pk_products;

-- [37/54] (rollback) drop_constraint: products
-- Reason: Inverse of add_constraint chk_products_price
ALTER TABLE products DROP CONSTRAINT IF EXISTS chk_products_price;

-- [38/54] (rollback) drop_constraint: product_categories
-- Reason: Inverse of add_constraint pk_product_categories
ALTER TABLE product_categories DROP CONSTRAINT IF EXISTS pk_product_categories;

-- [39/54] (rollback) drop_constraint: orders
-- Reason: Inverse of add_constraint pk_orders
ALTER TABLE orders DROP CONSTRAINT IF EXISTS pk_orders;

-- [40/54] (rollback) drop_constraint: order_items
-- Reason: Inverse of add_constraint pk_order_items
ALTER TABLE order_items DROP CONSTRAINT IF EXISTS pk_order_items;

-- [41/54] (rollback) drop_constraint: products
-- Reason: Inverse of add_constraint fk_products_product_categories
ALTER TABLE products DROP CONSTRAINT IF EXISTS fk_products_product_categories;

-- [42/54] (rollback) drop_constraint: orders
-- Reason: Inverse of add_constraint fk_orders_users
ALTER TABLE orders DROP CONSTRAINT IF EXISTS fk_orders_users;

-- [43/54] (rollback) drop_constraint: order_items
-- Reason: Inverse of add_constraint fk_order_items_products
ALTER TABLE order_items DROP CONSTRAINT IF EXISTS fk_order_items_products;

-- [44/54] (rollback) drop_constraint: order_items
-- Reason: Inverse of add_constraint fk_order_items_orders
ALTER TABLE order_items DROP CONSTRAINT IF EXISTS fk_order_items_orders;

-- [45/54] (rollback) drop_index: users
-- Reason: Inverse of add_index uniq_users_username
DROP INDEX IF EXISTS uniq_users_username;

-- [46/54] (rollback) drop_index: users
-- Reason: Inverse of add_index uniq_users_email
DROP INDEX IF EXISTS uniq_users_email;

-- [47/54] (rollback) drop_index: products
-- Reason: Inverse of add_index uniq_products_slug
DROP INDEX IF EXISTS uniq_products_slug;

-- [48/54] (rollback) drop_index: products
-- Reason: Inverse of add_index idx_products_category_id
DROP INDEX IF EXISTS idx_products_category_id;

-- [49/54] (rollback) drop_index: product_categories
-- Reason: Inverse of add_index uniq_product_categories_slug
DROP INDEX IF EXISTS uniq_product_categories_slug;

-- [50/54] (rollback) drop_index: orders
-- Reason: Inverse of add_index idx_orders_user_id
DROP INDEX IF EXISTS idx_orders_user_id;

-- [51/54] (rollback) add_table: sysdiagrams
-- Reason: Manual rollback required for dropped table
-- REQUIRES MANUAL COMPLETION
-- Forward migration dropped table "sysdiagrams". Data cannot be recovered automatically.
-- To complete:
--   Option A: restore from backup.
--   Option B: uncomment and fill in:
-- CREATE TABLE sysdiagrams (
--     -- TODO: original columns here
-- );

-- [52/54] (rollback) add_table: _migrate_history
-- Reason: Manual rollback required for dropped table
-- REQUIRES MANUAL COMPLETION
-- Forward migration dropped table "_migrate_history". Data cannot be recovered automatically.
-- To complete:
--   Option A: restore from backup.
--   Option B: uncomment and fill in:
-- CREATE TABLE _migrate_history (
--     -- TODO: original columns here
-- );

-- [53/54] (rollback) rename_table: product_categories
-- Reason: Inverse of rename_table categories -> product_categories
EXEC sp_rename 'product_categories', 'categories';

-- [54/54] (rollback) rename_column: products.description
-- Reason: Inverse of rename_column products.description -> details
ALTER TABLE products RENAME COLUMN details TO description;

