-- go-migrate-safe v0.1.0
-- Version: 2
-- Name: rename_products_details_and_more
-- Direction: UP
-- Generated: 2026-08-14T15:27:24Z
-- Checksum: sha256:3fd70e48ba61f064cc079eea22f7fad48e578a0c81a0498e362104f40add24a5
--
-- Operations (54):
--   [1] rename_column: products.details
--   [2] rename_table: categories
--   [3] drop_table: _migrate_history
--   [4] drop_table: sysdiagrams
--   [5] add_index: orders
--   [6] add_index: product_categories
--   [7] add_index: products
--   [8] add_index: products
--   [9] add_index: users
--   [10] add_index: users
--   [11] add_constraint: order_items
--   [12] add_constraint: order_items
--   [13] add_constraint: orders
--   [14] add_constraint: products
--   [15] add_constraint: order_items
--   [16] add_constraint: orders
--   [17] add_constraint: product_categories
--   [18] add_constraint: products
--   [19] add_constraint: products
--   [20] add_constraint: users
--   [21] alter_column: order_items.id
--   [22] alter_column: order_items.order_id
--   [23] alter_column: order_items.product_id
--   [24] alter_column: order_items.quantity
--   [25] alter_column: order_items.price
--   [26] alter_column: order_items.created_at
--   [27] alter_column: orders.id
--   [28] alter_column: orders.user_id
--   [29] alter_column: orders.status
--   [30] alter_column: orders.total
--   [31] alter_column: orders.created_at
--   [32] alter_column: orders.updated_at
--   [33] alter_column: product_categories.id
--   [34] alter_column: product_categories.name
--   [35] alter_column: product_categories.slug
--   [36] alter_column: product_categories.description
--   [37] alter_column: product_categories.created_at
--   [38] alter_column: products.id
--   [39] alter_column: products.category_id
--   [40] alter_column: products.name
--   [41] alter_column: products.slug
--   [42] alter_column: products.details
--   [43] alter_column: products.price
--   [44] alter_column: products.stock
--   [45] alter_column: products.image_url
--   [46] alter_column: products.created_at
--   [47] alter_column: products.updated_at
--   [48] alter_column: users.id
--   [49] alter_column: users.username
--   [50] alter_column: users.email
--   [51] alter_column: users.password_hash
--   [52] alter_column: users.role
--   [53] alter_column: users.created_at
--   [54] alter_column: users.updated_at
--
-- DO NOT EDIT this file after it has been applied to any environment.
-- To change the schema, create a new migration.

-- Logic: Grouped by table for performance
-- [1/54] rename_column: products.details (Reason: Rename column "products"."description" → "details" (explicit struct tag))
-- [2/54] rename_table: categories (Reason: Rename table "categories" → "product_categories" (explicit struct tag))
-- [3/54] drop_table: _migrate_history (Reason: Removed "_migrate_history" table — no corresponding struct model found)
-- [4/54] drop_table: sysdiagrams (Reason: Removed "sysdiagrams" table — no corresponding struct model found)
-- [5/54] add_index: orders (Reason: Added index "idx_orders_user_id" on orders(user_id))
-- [6/54] add_index: product_categories (Reason: Added index "uniq_product_categories_slug" on product_categories(slug))
-- [7/54] add_index: products (Reason: Added index "idx_products_category_id" on products(category_id))
-- [8/54] add_index: products (Reason: Added index "uniq_products_slug" on products(slug))
-- [9/54] add_index: users (Reason: Added index "uniq_users_email" on users(email))
-- [10/54] add_index: users (Reason: Added index "uniq_users_username" on users(username))
-- [11/54] add_constraint: order_items (Reason: Added constraint "fk_order_items_orders" (fk))
-- [12/54] add_constraint: order_items (Reason: Added constraint "fk_order_items_products" (fk))
-- [13/54] add_constraint: orders (Reason: Added constraint "fk_orders_users" (fk))
-- [14/54] add_constraint: products (Reason: Added constraint "fk_products_product_categories" (fk))
-- [15/54] add_constraint: order_items (Reason: Added constraint "pk_order_items" (pk))
-- [16/54] add_constraint: orders (Reason: Added constraint "pk_orders" (pk))
-- [17/54] add_constraint: product_categories (Reason: Added constraint "pk_product_categories" (pk))
-- [18/54] add_constraint: products (Reason: Added constraint "chk_products_price" (check))
-- [19/54] add_constraint: products (Reason: Added constraint "pk_products" (pk))
-- [20/54] add_constraint: users (Reason: Added constraint "pk_users" (pk))
-- [21/54] alter_column: order_items.id (Reason: Changed "order_items"."id": bigint → BIGINT)
-- [22/54] alter_column: order_items.order_id (Reason: Changed "order_items"."order_id": bigint → BIGINT)
-- [23/54] alter_column: order_items.product_id (Reason: Changed "order_items"."product_id": bigint → BIGINT)
-- [24/54] alter_column: order_items.quantity (Reason: Changed "order_items"."quantity": int → INT; default changed)
-- [25/54] alter_column: order_items.price (Reason: Changed "order_items"."price": float → FLOAT)
-- [26/54] alter_column: order_items.created_at (Reason: Changed "order_items"."created_at": datetime2 → DATETIME2; default changed)
-- [27/54] alter_column: orders.id (Reason: Changed "orders"."id": bigint → BIGINT)
-- [28/54] alter_column: orders.user_id (Reason: Changed "orders"."user_id": bigint → BIGINT)
-- [29/54] alter_column: orders.status (Reason: Changed "orders"."status": nvarchar → NVARCHAR(MAX); default changed)
-- [30/54] alter_column: orders.total (Reason: Changed "orders"."total": float → FLOAT; default changed)
-- [31/54] alter_column: orders.created_at (Reason: Changed "orders"."created_at": datetime2 → DATETIME2; default changed)
-- [32/54] alter_column: orders.updated_at (Reason: Changed "orders"."updated_at": datetime2 → DATETIME2; default changed)
-- [33/54] alter_column: product_categories.id (Reason: Changed "product_categories"."id": bigint → BIGINT)
-- [34/54] alter_column: product_categories.name (Reason: Changed "product_categories"."name": nvarchar → NVARCHAR(MAX))
-- [35/54] alter_column: product_categories.slug (Reason: Changed "product_categories"."slug": nvarchar → NVARCHAR(MAX); size changed)
-- [36/54] alter_column: product_categories.description (Reason: Changed "product_categories"."description": nvarchar → NVARCHAR(MAX))
-- [37/54] alter_column: product_categories.created_at (Reason: Changed "product_categories"."created_at": datetime2 → DATETIME2; default changed)
-- [38/54] alter_column: products.id (Reason: Changed "products"."id": bigint → BIGINT)
-- [39/54] alter_column: products.category_id (Reason: Changed "products"."category_id": bigint → BIGINT)
-- [40/54] alter_column: products.name (Reason: Changed "products"."name": nvarchar → NVARCHAR(MAX))
-- [41/54] alter_column: products.slug (Reason: Changed "products"."slug": nvarchar → NVARCHAR(MAX); size changed)
-- [42/54] alter_column: products.details (Reason: Changed "products"."details": nvarchar → NVARCHAR(MAX))
-- [43/54] alter_column: products.price (Reason: Changed "products"."price": float → FLOAT; default changed)
-- [44/54] alter_column: products.stock (Reason: Changed "products"."stock": int → INT; default changed)
-- [45/54] alter_column: products.image_url (Reason: Changed "products"."image_url": nvarchar → NVARCHAR(MAX))
-- [46/54] alter_column: products.created_at (Reason: Changed "products"."created_at": datetime2 → DATETIME2; default changed)
-- [47/54] alter_column: products.updated_at (Reason: Changed "products"."updated_at": datetime2 → DATETIME2; default changed)
-- [48/54] alter_column: users.id (Reason: Changed "users"."id": bigint → BIGINT)
-- [49/54] alter_column: users.username (Reason: Changed "users"."username": nvarchar → NVARCHAR(MAX))
-- [50/54] alter_column: users.email (Reason: Changed "users"."email": nvarchar → NVARCHAR(MAX))
-- [51/54] alter_column: users.password_hash (Reason: Changed "users"."password_hash": nvarchar → NVARCHAR(MAX))
-- [52/54] alter_column: users.role (Reason: Changed "users"."role": nvarchar → NVARCHAR(MAX); default changed)
-- [53/54] alter_column: users.created_at (Reason: Changed "users"."created_at": datetime2 → DATETIME2; default changed)
-- [54/54] alter_column: users.updated_at (Reason: Changed "users"."updated_at": datetime2 → DATETIME2; default changed)

EXEC sp_rename 'products.description', 'details', 'COLUMN';

EXEC sp_rename 'categories', 'product_categories';

DROP TABLE IF EXISTS _migrate_history;

DROP TABLE IF EXISTS sysdiagrams;

CREATE INDEX idx_orders_user_id ON orders (user_id);

CREATE UNIQUE INDEX uniq_product_categories_slug ON product_categories (slug);

CREATE INDEX idx_products_category_id ON products (category_id);

CREATE UNIQUE INDEX uniq_products_slug ON products (slug);

CREATE UNIQUE INDEX uniq_users_email ON users (email);

CREATE UNIQUE INDEX uniq_users_username ON users (username);

ALTER TABLE order_items ADD CONSTRAINT fk_order_items_orders FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_items ADD CONSTRAINT fk_order_items_products FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE orders ADD CONSTRAINT fk_orders_users FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE products ADD CONSTRAINT fk_products_product_categories FOREIGN KEY (category_id) REFERENCES product_categories (id);

ALTER TABLE order_items ADD CONSTRAINT pk_order_items PRIMARY KEY (id);

ALTER TABLE orders ADD CONSTRAINT pk_orders PRIMARY KEY (id);

ALTER TABLE product_categories ADD CONSTRAINT pk_product_categories PRIMARY KEY (id);

ALTER TABLE products ADD CONSTRAINT chk_products_price CHECK (price >= 0);

ALTER TABLE products ADD CONSTRAINT pk_products PRIMARY KEY (id);

ALTER TABLE users ADD CONSTRAINT pk_users PRIMARY KEY (id);

ALTER TABLE order_items ALTER COLUMN id BIGINT IDENTITY(1,1) NOT NULL;

ALTER TABLE order_items ALTER COLUMN order_id BIGINT NOT NULL;

ALTER TABLE order_items ALTER COLUMN product_id BIGINT NOT NULL;

ALTER TABLE order_items ALTER COLUMN quantity INT NOT NULL;
ALTER TABLE order_items ADD CONSTRAINT DF_order_items_quantity DEFAULT 1 FOR quantity;

ALTER TABLE order_items ALTER COLUMN price FLOAT NOT NULL;

ALTER TABLE order_items ALTER COLUMN created_at DATETIME2 NOT NULL;
ALTER TABLE order_items ADD CONSTRAINT DF_order_items_created_at DEFAULT CURRENT_TIMESTAMP FOR created_at;

ALTER TABLE orders ALTER COLUMN id BIGINT IDENTITY(1,1) NOT NULL;

ALTER TABLE orders ALTER COLUMN user_id BIGINT NOT NULL;

ALTER TABLE orders ALTER COLUMN status NVARCHAR(255) NOT NULL;
ALTER TABLE orders ADD CONSTRAINT DF_orders_status DEFAULT 'pending' FOR status;

ALTER TABLE orders ALTER COLUMN total FLOAT NOT NULL;
ALTER TABLE orders ADD CONSTRAINT DF_orders_total DEFAULT 0.00 FOR total;

ALTER TABLE orders ALTER COLUMN created_at DATETIME2 NOT NULL;
ALTER TABLE orders ADD CONSTRAINT DF_orders_created_at DEFAULT CURRENT_TIMESTAMP FOR created_at;

ALTER TABLE orders ALTER COLUMN updated_at DATETIME2 NOT NULL;
ALTER TABLE orders ADD CONSTRAINT DF_orders_updated_at DEFAULT CURRENT_TIMESTAMP FOR updated_at;

ALTER TABLE product_categories ALTER COLUMN id BIGINT IDENTITY(1,1) NOT NULL;

ALTER TABLE product_categories ALTER COLUMN name NVARCHAR(MAX) NOT NULL;

ALTER TABLE product_categories ALTER COLUMN slug NVARCHAR(MAX) NOT NULL;

ALTER TABLE product_categories ALTER COLUMN description NVARCHAR(MAX) NOT NULL;

ALTER TABLE product_categories ALTER COLUMN created_at DATETIME2 NOT NULL;
ALTER TABLE product_categories ADD CONSTRAINT DF_product_categories_created_at DEFAULT GETDATE() FOR created_at;

ALTER TABLE products ALTER COLUMN id BIGINT IDENTITY(1,1) NOT NULL;

ALTER TABLE products ALTER COLUMN category_id BIGINT NOT NULL;

ALTER TABLE products ALTER COLUMN name NVARCHAR(MAX) NOT NULL;

ALTER TABLE products ALTER COLUMN slug NVARCHAR(MAX) NOT NULL;

ALTER TABLE products ALTER COLUMN details NVARCHAR(MAX) NOT NULL;

ALTER TABLE products ALTER COLUMN price FLOAT NOT NULL;
ALTER TABLE products ADD CONSTRAINT DF_products_price DEFAULT 0.00 FOR price;

ALTER TABLE products ALTER COLUMN stock INT NOT NULL;
ALTER TABLE products ADD CONSTRAINT DF_products_stock DEFAULT 0 FOR stock;

ALTER TABLE products ALTER COLUMN image_url NVARCHAR(MAX) NOT NULL;

ALTER TABLE products ALTER COLUMN created_at DATETIME2 NOT NULL;
ALTER TABLE products ADD CONSTRAINT DF_products_created_at DEFAULT CURRENT_TIMESTAMP FOR created_at;

ALTER TABLE products ALTER COLUMN updated_at DATETIME2 NOT NULL;
ALTER TABLE products ADD CONSTRAINT DF_products_updated_at DEFAULT CURRENT_TIMESTAMP FOR updated_at;

ALTER TABLE users ALTER COLUMN id BIGINT IDENTITY(1,1) NOT NULL;

ALTER TABLE users ALTER COLUMN username NVARCHAR(MAX) NOT NULL;

ALTER TABLE users ALTER COLUMN email NVARCHAR(MAX) NOT NULL;

ALTER TABLE users ALTER COLUMN password_hash NVARCHAR(MAX) NOT NULL;

ALTER TABLE users ALTER COLUMN role NVARCHAR(255) NOT NULL;
ALTER TABLE users ADD CONSTRAINT DF_users_role DEFAULT 'user' FOR role;

ALTER TABLE users ALTER COLUMN created_at DATETIME2 NOT NULL;
ALTER TABLE users ADD CONSTRAINT DF_users_created_at DEFAULT CURRENT_TIMESTAMP FOR created_at;

ALTER TABLE users ALTER COLUMN updated_at DATETIME2 NOT NULL;
ALTER TABLE users ADD CONSTRAINT DF_users_updated_at DEFAULT CURRENT_TIMESTAMP FOR updated_at;
