-- go-migrate-safe v0.1.0
-- Version: 1
-- Name: add_categories_table_and_add_order_items_table
-- Direction: UP
-- Generated: 2026-05-08T02:18:42Z
-- Checksum: sha256:f1140dcc791c28480ead1cd8c0800ee9664f271fff18ff12792a3989f4e0a21d
--
-- Operations (5):
--   [1] add_table: categories
--   [2] add_table: order_items
--   [3] add_table: orders
--   [4] add_table: products
--   [5] add_table: users
--
-- DO NOT EDIT this file after it has been applied to any environment.
-- To change the schema, create a new migration.

-- [1/5] add_table: categories
-- Reason: Added "categories" table (5 columns) — matches new struct
CREATE TABLE IF NOT EXISTS categories (
    id           BIGINT AUTO_INCREMENT NOT NULL,
    name         TEXT                  NOT NULL,
    slug         TEXT                  NOT NULL,
    description  TEXT                  NOT NULL,
    created_at   DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB;

-- [2/5] add_table: order_items
-- Reason: Added "order_items" table (6 columns) — matches new struct
CREATE TABLE IF NOT EXISTS order_items (
    id          BIGINT AUTO_INCREMENT NOT NULL,
    order_id    BIGINT                NOT NULL,
    product_id  BIGINT                NOT NULL,
    quantity    INTEGER               NOT NULL DEFAULT 1,
    price       DOUBLE                NOT NULL,
    created_at  DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB;

-- [3/5] add_table: orders
-- Reason: Added "orders" table (6 columns) — matches new struct
CREATE TABLE IF NOT EXISTS orders (
    id          BIGINT AUTO_INCREMENT NOT NULL,
    user_id     BIGINT                NOT NULL,
    status      VARCHAR(255)          NOT NULL DEFAULT 'pending',
    total       DOUBLE                NOT NULL DEFAULT 0.00,
    created_at  DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB;

-- [4/5] add_table: products
-- Reason: Added "products" table (10 columns) — matches new struct
CREATE TABLE IF NOT EXISTS products (
    id           BIGINT AUTO_INCREMENT NOT NULL,
    category_id  BIGINT                NOT NULL,
    name         TEXT                  NOT NULL,
    slug         TEXT                  NOT NULL,
    description  TEXT                  NOT NULL,
    price        DOUBLE                NOT NULL DEFAULT 0.00,
    stock        INTEGER               NOT NULL DEFAULT 0,
    image_url    TEXT                  NOT NULL,
    created_at   DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB;

-- [5/5] add_table: users
-- Reason: Added "users" table (7 columns) — matches new struct
CREATE TABLE IF NOT EXISTS users (
    id             BIGINT AUTO_INCREMENT NOT NULL,
    username       TEXT                  NOT NULL,
    email          TEXT                  NOT NULL,
    password_hash  TEXT                  NOT NULL,
    role           VARCHAR(255)          NOT NULL DEFAULT 'user',
    created_at     DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB;
