-- go-migrate-safe v0.1.0
-- Version: 2
-- Name: add_uniq_product_categories_slug_and_more
-- Direction: DOWN
-- Generated: 2026-08-14T15:31:58Z
--
-- Operations (49):
--   [1] add_index: product_categories
--   [2] add_index: products
--   [3] add_index: products
--   [4] add_index: users
--   [5] add_index: users
--   [6] add_constraint: order_items
--   [7] add_constraint: order_items
--   [8] add_constraint: orders
--   [9] add_constraint: products
--   [10] add_constraint: order_items
--   [11] add_constraint: orders
--   [12] add_constraint: product_categories
--   [13] add_constraint: products
--   [14] add_constraint: products
--   [15] add_constraint: users
--   [16] alter_column: order_items.id
--   [17] alter_column: order_items.order_id
--   [18] alter_column: order_items.product_id
--   [19] alter_column: order_items.quantity
--   [20] alter_column: order_items.price
--   [21] alter_column: order_items.created_at
--   [22] alter_column: orders.id
--   [23] alter_column: orders.user_id
--   [24] alter_column: orders.status
--   [25] alter_column: orders.total
--   [26] alter_column: orders.created_at
--   [27] alter_column: orders.updated_at
--   [28] alter_column: product_categories.id
--   [29] alter_column: product_categories.name
--   [30] alter_column: product_categories.slug
--   [31] alter_column: product_categories.description
--   [32] alter_column: product_categories.created_at
--   [33] alter_column: products.id
--   [34] alter_column: products.category_id
--   [35] alter_column: products.name
--   [36] alter_column: products.slug
--   [37] alter_column: products.details
--   [38] alter_column: products.price
--   [39] alter_column: products.stock
--   [40] alter_column: products.image_url
--   [41] alter_column: products.created_at
--   [42] alter_column: products.updated_at
--   [43] alter_column: users.id
--   [44] alter_column: users.username
--   [45] alter_column: users.email
--   [46] alter_column: users.password_hash
--   [47] alter_column: users.role
--   [48] alter_column: users.created_at
--   [49] alter_column: users.updated_at
--
-- DO NOT EDIT this file after it has been applied to any environment.
-- To change the schema, create a new migration.

-- Rollback SQL to be populated by Rollback Agent.

-- [1/49] (rollback) alter_column: users.updated_at
-- Reason: Inverse of alter_column users.updated_at
ALTER TABLE users MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- [2/49] (rollback) alter_column: users.created_at
-- Reason: Inverse of alter_column users.created_at
ALTER TABLE users MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- [3/49] (rollback) alter_column: users.role
-- Reason: Inverse of alter_column users.role
ALTER TABLE users MODIFY COLUMN role varchar NOT NULL DEFAULT 'user';

-- [4/49] (rollback) alter_column: users.password_hash
-- Reason: Inverse of alter_column users.password_hash
ALTER TABLE users MODIFY COLUMN password_hash text NOT NULL;

-- [5/49] (rollback) alter_column: users.email
-- Reason: Inverse of alter_column users.email
ALTER TABLE users MODIFY COLUMN email text NOT NULL;

-- [6/49] (rollback) alter_column: users.username
-- Reason: Inverse of alter_column users.username
ALTER TABLE users MODIFY COLUMN username text NOT NULL;

-- [7/49] (rollback) alter_column: users.id
-- Reason: Inverse of alter_column users.id
ALTER TABLE users MODIFY COLUMN id bigint NOT NULL;

-- [8/49] (rollback) alter_column: products.updated_at
-- Reason: Inverse of alter_column products.updated_at
ALTER TABLE products MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- [9/49] (rollback) alter_column: products.created_at
-- Reason: Inverse of alter_column products.created_at
ALTER TABLE products MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- [10/49] (rollback) alter_column: products.image_url
-- Reason: Inverse of alter_column products.image_url
ALTER TABLE products MODIFY COLUMN image_url text NOT NULL;

-- [11/49] (rollback) alter_column: products.stock
-- Reason: Inverse of alter_column products.stock
ALTER TABLE products MODIFY COLUMN stock int NOT NULL DEFAULT 0;

-- [12/49] (rollback) alter_column: products.price
-- Reason: Inverse of alter_column products.price
ALTER TABLE products MODIFY COLUMN price double NOT NULL DEFAULT 0;

-- [13/49] (rollback) alter_column: products.details
-- Reason: Inverse of alter_column products.details
ALTER TABLE products MODIFY COLUMN details text NOT NULL;

-- [14/49] (rollback) alter_column: products.slug
-- Reason: Inverse of alter_column products.slug
ALTER TABLE products MODIFY COLUMN slug text NOT NULL;

-- [15/49] (rollback) alter_column: products.name
-- Reason: Inverse of alter_column products.name
ALTER TABLE products MODIFY COLUMN name text NOT NULL;

-- [16/49] (rollback) alter_column: products.category_id
-- Reason: Inverse of alter_column products.category_id
ALTER TABLE products MODIFY COLUMN category_id bigint NOT NULL;

-- [17/49] (rollback) alter_column: products.id
-- Reason: Inverse of alter_column products.id
ALTER TABLE products MODIFY COLUMN id bigint NOT NULL;

-- [18/49] (rollback) alter_column: product_categories.created_at
-- Reason: Inverse of alter_column product_categories.created_at
ALTER TABLE product_categories MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- [19/49] (rollback) alter_column: product_categories.description
-- Reason: Inverse of alter_column product_categories.description
ALTER TABLE product_categories MODIFY COLUMN description text NOT NULL;

-- [20/49] (rollback) alter_column: product_categories.slug
-- Reason: Inverse of alter_column product_categories.slug
ALTER TABLE product_categories MODIFY COLUMN slug text NOT NULL;

-- [21/49] (rollback) alter_column: product_categories.name
-- Reason: Inverse of alter_column product_categories.name
ALTER TABLE product_categories MODIFY COLUMN name text NOT NULL;

-- [22/49] (rollback) alter_column: product_categories.id
-- Reason: Inverse of alter_column product_categories.id
ALTER TABLE product_categories MODIFY COLUMN id bigint NOT NULL;

-- [23/49] (rollback) alter_column: orders.updated_at
-- Reason: Inverse of alter_column orders.updated_at
ALTER TABLE orders MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- [24/49] (rollback) alter_column: orders.created_at
-- Reason: Inverse of alter_column orders.created_at
ALTER TABLE orders MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- [25/49] (rollback) alter_column: orders.total
-- Reason: Inverse of alter_column orders.total
ALTER TABLE orders MODIFY COLUMN total double NOT NULL DEFAULT 0;

-- [26/49] (rollback) alter_column: orders.status
-- Reason: Inverse of alter_column orders.status
ALTER TABLE orders MODIFY COLUMN status varchar NOT NULL DEFAULT 'pending';

-- [27/49] (rollback) alter_column: orders.user_id
-- Reason: Inverse of alter_column orders.user_id
ALTER TABLE orders MODIFY COLUMN user_id bigint NOT NULL;

-- [28/49] (rollback) alter_column: orders.id
-- Reason: Inverse of alter_column orders.id
ALTER TABLE orders MODIFY COLUMN id bigint NOT NULL;

-- [29/49] (rollback) alter_column: order_items.created_at
-- Reason: Inverse of alter_column order_items.created_at
ALTER TABLE order_items MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- [30/49] (rollback) alter_column: order_items.price
-- Reason: Inverse of alter_column order_items.price
ALTER TABLE order_items MODIFY COLUMN price double NOT NULL;

-- [31/49] (rollback) alter_column: order_items.quantity
-- Reason: Inverse of alter_column order_items.quantity
ALTER TABLE order_items MODIFY COLUMN quantity int NOT NULL DEFAULT 1;

-- [32/49] (rollback) alter_column: order_items.product_id
-- Reason: Inverse of alter_column order_items.product_id
ALTER TABLE order_items MODIFY COLUMN product_id bigint NOT NULL;

-- [33/49] (rollback) alter_column: order_items.order_id
-- Reason: Inverse of alter_column order_items.order_id
ALTER TABLE order_items MODIFY COLUMN order_id bigint NOT NULL;

-- [34/49] (rollback) alter_column: order_items.id
-- Reason: Inverse of alter_column order_items.id
ALTER TABLE order_items MODIFY COLUMN id bigint NOT NULL;

-- [35/49] (rollback) drop_constraint: users
-- Reason: Inverse of add_constraint pk_users
ALTER TABLE users DROP CONSTRAINT IF EXISTS pk_users;

-- [36/49] (rollback) drop_constraint: products
-- Reason: Inverse of add_constraint pk_products
ALTER TABLE products DROP CONSTRAINT IF EXISTS pk_products;

-- [37/49] (rollback) drop_constraint: products
-- Reason: Inverse of add_constraint chk_products_price
ALTER TABLE products DROP CONSTRAINT IF EXISTS chk_products_price;

-- [38/49] (rollback) drop_constraint: product_categories
-- Reason: Inverse of add_constraint pk_product_categories
ALTER TABLE product_categories DROP CONSTRAINT IF EXISTS pk_product_categories;

-- [39/49] (rollback) drop_constraint: orders
-- Reason: Inverse of add_constraint pk_orders
ALTER TABLE orders DROP CONSTRAINT IF EXISTS pk_orders;

-- [40/49] (rollback) drop_constraint: order_items
-- Reason: Inverse of add_constraint pk_order_items
ALTER TABLE order_items DROP CONSTRAINT IF EXISTS pk_order_items;

-- [41/49] (rollback) drop_constraint: products
-- Reason: Inverse of add_constraint fk_products_product_categories
ALTER TABLE products DROP CONSTRAINT IF EXISTS fk_products_product_categories;

-- [42/49] (rollback) drop_constraint: orders
-- Reason: Inverse of add_constraint fk_orders_users
ALTER TABLE orders DROP CONSTRAINT IF EXISTS fk_orders_users;

-- [43/49] (rollback) drop_constraint: order_items
-- Reason: Inverse of add_constraint fk_order_items_products
ALTER TABLE order_items DROP CONSTRAINT IF EXISTS fk_order_items_products;

-- [44/49] (rollback) drop_constraint: order_items
-- Reason: Inverse of add_constraint fk_order_items_orders
ALTER TABLE order_items DROP CONSTRAINT IF EXISTS fk_order_items_orders;

-- [45/49] (rollback) drop_index: users
-- Reason: Inverse of add_index uniq_users_username
DROP INDEX IF EXISTS uniq_users_username;

-- [46/49] (rollback) drop_index: users
-- Reason: Inverse of add_index uniq_users_email
DROP INDEX IF EXISTS uniq_users_email;

-- [47/49] (rollback) drop_index: products
-- Reason: Inverse of add_index uniq_products_slug
DROP INDEX IF EXISTS uniq_products_slug;

-- [48/49] (rollback) drop_index: products
-- Reason: Inverse of add_index idx_products_category_id
DROP INDEX IF EXISTS idx_products_category_id;

-- [49/49] (rollback) drop_index: product_categories
-- Reason: Inverse of add_index uniq_product_categories_slug
DROP INDEX IF EXISTS uniq_product_categories_slug;

