-- go-migrate-safe v0.1.0
-- Version: 2
-- Name: add_uniq_product_categories_slug_and_more
-- Direction: UP
-- Generated: 2026-08-14T15:31:58Z
-- Checksum: sha256:d27209addb6b3fc430b4e64e0aee5a60385bc4f773a0dbe7fcd485d4e0bbfe1d
--
-- Operations (49):
--   [1] add_index: product_categories
--   [2] add_index: products
--   [3] add_index: products
--   [4] add_index: users
--   [5] add_index: users
--   [6] add_constraint: order_items
--   [7] add_constraint: order_items
--   [8] add_constraint: orders
--   [9] add_constraint: products
--   [10] add_constraint: order_items
--   [11] add_constraint: orders
--   [12] add_constraint: product_categories
--   [13] add_constraint: products
--   [14] add_constraint: products
--   [15] add_constraint: users
--   [16] alter_column: order_items.id
--   [17] alter_column: order_items.order_id
--   [18] alter_column: order_items.product_id
--   [19] alter_column: order_items.quantity
--   [20] alter_column: order_items.price
--   [21] alter_column: order_items.created_at
--   [22] alter_column: orders.id
--   [23] alter_column: orders.user_id
--   [24] alter_column: orders.status
--   [25] alter_column: orders.total
--   [26] alter_column: orders.created_at
--   [27] alter_column: orders.updated_at
--   [28] alter_column: product_categories.id
--   [29] alter_column: product_categories.name
--   [30] alter_column: product_categories.slug
--   [31] alter_column: product_categories.description
--   [32] alter_column: product_categories.created_at
--   [33] alter_column: products.id
--   [34] alter_column: products.category_id
--   [35] alter_column: products.name
--   [36] alter_column: products.slug
--   [37] alter_column: products.details
--   [38] alter_column: products.price
--   [39] alter_column: products.stock
--   [40] alter_column: products.image_url
--   [41] alter_column: products.created_at
--   [42] alter_column: products.updated_at
--   [43] alter_column: users.id
--   [44] alter_column: users.username
--   [45] alter_column: users.email
--   [46] alter_column: users.password_hash
--   [47] alter_column: users.role
--   [48] alter_column: users.created_at
--   [49] alter_column: users.updated_at
--
-- DO NOT EDIT this file after it has been applied to any environment.
-- To change the schema, create a new migration.

-- Logic: Grouped by table for performance
-- [1/49] add_index: product_categories (Reason: Added index "uniq_product_categories_slug" on product_categories(slug))
-- [2/49] add_index: products (Reason: Added index "idx_products_category_id" on products(category_id))
-- [3/49] add_index: products (Reason: Added index "uniq_products_slug" on products(slug))
-- [4/49] add_index: users (Reason: Added index "uniq_users_email" on users(email))
-- [5/49] add_index: users (Reason: Added index "uniq_users_username" on users(username))
-- [6/49] add_constraint: order_items (Reason: Added constraint "fk_order_items_orders" (fk))
-- [7/49] add_constraint: order_items (Reason: Added constraint "fk_order_items_products" (fk))
-- [8/49] add_constraint: orders (Reason: Added constraint "fk_orders_users" (fk))
-- [9/49] add_constraint: products (Reason: Added constraint "fk_products_product_categories" (fk))
-- [10/49] add_constraint: order_items (Reason: Added constraint "pk_order_items" (pk))
-- [11/49] add_constraint: orders (Reason: Added constraint "pk_orders" (pk))
-- [12/49] add_constraint: product_categories (Reason: Added constraint "pk_product_categories" (pk))
-- [13/49] add_constraint: products (Reason: Added constraint "chk_products_price" (check))
-- [14/49] add_constraint: products (Reason: Added constraint "pk_products" (pk))
-- [15/49] add_constraint: users (Reason: Added constraint "pk_users" (pk))
-- [16/49] alter_column: order_items.id (Reason: Changed "order_items"."id": bigint → BIGINT)
-- [17/49] alter_column: order_items.order_id (Reason: Changed "order_items"."order_id": bigint → BIGINT)
-- [18/49] alter_column: order_items.product_id (Reason: Changed "order_items"."product_id": bigint → BIGINT)
-- [19/49] alter_column: order_items.quantity (Reason: Changed "order_items"."quantity": int → INT)
-- [20/49] alter_column: order_items.price (Reason: Changed "order_items"."price": double → DOUBLE)
-- [21/49] alter_column: order_items.created_at (Reason: Changed "order_items"."created_at": datetime → DATETIME)
-- [22/49] alter_column: orders.id (Reason: Changed "orders"."id": bigint → BIGINT)
-- [23/49] alter_column: orders.user_id (Reason: Changed "orders"."user_id": bigint → BIGINT)
-- [24/49] alter_column: orders.status (Reason: Changed "orders"."status": varchar → TEXT)
-- [25/49] alter_column: orders.total (Reason: Changed "orders"."total": double → DOUBLE; default changed)
-- [26/49] alter_column: orders.created_at (Reason: Changed "orders"."created_at": datetime → DATETIME)
-- [27/49] alter_column: orders.updated_at (Reason: Changed "orders"."updated_at": datetime → DATETIME)
-- [28/49] alter_column: product_categories.id (Reason: Changed "product_categories"."id": bigint → BIGINT)
-- [29/49] alter_column: product_categories.name (Reason: Changed "product_categories"."name": text → TEXT)
-- [30/49] alter_column: product_categories.slug (Reason: Changed "product_categories"."slug": text → VARCHAR(255); size changed)
-- [31/49] alter_column: product_categories.description (Reason: Changed "product_categories"."description": text → TEXT)
-- [32/49] alter_column: product_categories.created_at (Reason: Changed "product_categories"."created_at": datetime → DATETIME)
-- [33/49] alter_column: products.id (Reason: Changed "products"."id": bigint → BIGINT)
-- [34/49] alter_column: products.category_id (Reason: Changed "products"."category_id": bigint → BIGINT)
-- [35/49] alter_column: products.name (Reason: Changed "products"."name": text → TEXT)
-- [36/49] alter_column: products.slug (Reason: Changed "products"."slug": text → VARCHAR(255); size changed)
-- [37/49] alter_column: products.details (Reason: Changed "products"."details": text → TEXT)
-- [38/49] alter_column: products.price (Reason: Changed "products"."price": double → DOUBLE; default changed)
-- [39/49] alter_column: products.stock (Reason: Changed "products"."stock": int → INT)
-- [40/49] alter_column: products.image_url (Reason: Changed "products"."image_url": text → TEXT)
-- [41/49] alter_column: products.created_at (Reason: Changed "products"."created_at": datetime → DATETIME)
-- [42/49] alter_column: products.updated_at (Reason: Changed "products"."updated_at": datetime → DATETIME)
-- [43/49] alter_column: users.id (Reason: Changed "users"."id": bigint → BIGINT)
-- [44/49] alter_column: users.username (Reason: Changed "users"."username": text → VARCHAR(255); size changed)
-- [45/49] alter_column: users.email (Reason: Changed "users"."email": text → VARCHAR(255); size changed)
-- [46/49] alter_column: users.password_hash (Reason: Changed "users"."password_hash": text → TEXT)
-- [47/49] alter_column: users.role (Reason: Changed "users"."role": varchar → TEXT)
-- [48/49] alter_column: users.created_at (Reason: Changed "users"."created_at": datetime → DATETIME)
-- [49/49] alter_column: users.updated_at (Reason: Changed "users"."updated_at": datetime → DATETIME)

ALTER TABLE product_categories ADD UNIQUE INDEX uniq_product_categories_slug (slug), ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE products ADD INDEX idx_products_category_id (category_id), ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE products ADD UNIQUE INDEX uniq_products_slug (slug), ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE users ADD UNIQUE INDEX uniq_users_email (email), ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE users ADD UNIQUE INDEX uniq_users_username (username), ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE order_items ADD CONSTRAINT fk_order_items_orders FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_items ADD CONSTRAINT fk_order_items_products FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE orders ADD CONSTRAINT fk_orders_users FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE products ADD CONSTRAINT fk_products_product_categories FOREIGN KEY (category_id) REFERENCES product_categories (id);

ALTER TABLE order_items ADD CONSTRAINT pk_order_items PRIMARY KEY (id);

ALTER TABLE orders ADD CONSTRAINT pk_orders PRIMARY KEY (id);

ALTER TABLE product_categories ADD CONSTRAINT pk_product_categories PRIMARY KEY (id);

ALTER TABLE products ADD CONSTRAINT chk_products_price CHECK (price >= 0);

ALTER TABLE products ADD CONSTRAINT pk_products PRIMARY KEY (id);

ALTER TABLE users ADD CONSTRAINT pk_users PRIMARY KEY (id);

ALTER TABLE order_items
    MODIFY COLUMN id BIGINT NOT NULL,
    MODIFY COLUMN order_id BIGINT NOT NULL,
    MODIFY COLUMN product_id BIGINT NOT NULL,
    MODIFY COLUMN quantity INT NOT NULL DEFAULT 1,
    MODIFY COLUMN price DOUBLE NOT NULL,
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE orders
    MODIFY COLUMN id BIGINT NOT NULL,
    MODIFY COLUMN user_id BIGINT NOT NULL,
    MODIFY COLUMN status TEXT NOT NULL DEFAULT 'pending',
    MODIFY COLUMN total DOUBLE NOT NULL DEFAULT 0.00,
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE product_categories
    MODIFY COLUMN id BIGINT NOT NULL,
    MODIFY COLUMN name TEXT NOT NULL,
    MODIFY COLUMN slug VARCHAR(255) NOT NULL,
    MODIFY COLUMN description TEXT NOT NULL,
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE products
    MODIFY COLUMN id BIGINT NOT NULL,
    MODIFY COLUMN category_id BIGINT NOT NULL,
    MODIFY COLUMN name TEXT NOT NULL,
    MODIFY COLUMN slug VARCHAR(255) NOT NULL,
    MODIFY COLUMN details TEXT NOT NULL,
    MODIFY COLUMN price DOUBLE NOT NULL DEFAULT 0.00,
    MODIFY COLUMN stock INT NOT NULL DEFAULT 0,
    MODIFY COLUMN image_url TEXT NOT NULL,
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
    MODIFY COLUMN id BIGINT NOT NULL,
    MODIFY COLUMN username VARCHAR(255) NOT NULL,
    MODIFY COLUMN email VARCHAR(255) NOT NULL,
    MODIFY COLUMN password_hash TEXT NOT NULL,
    MODIFY COLUMN role TEXT NOT NULL DEFAULT 'user',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
